### PR TITLE
Scikit-learn 19.0 updates on .fit( ) arguments

### PR DESCRIPTION
**Pull request by ChrisQlasty**
Adopting code to my needs I have found that in the scikit-learn 19.0  they recommend to put params list directly into the .fit( ) method. It looks like a good change as that makes the code more understandable for me - now it is more clear where these values go to (fit( ) function of DNNClassifier).
Hope this makes sense.

### CODE REVIEW

**Comment by ageron** [comment]
Hi @ChrisQlasty ,
Thanks a lot for this PR, it's a very interesting point. The only problem is that many people still use scikit-learn 0.18, so they would get an error. For now, I prefer to leave the existing code in place, but I will add a comment to explain your point (or if you want to do it, please update your PR).
Thanks again.

**Comment by ChrisQlasty** [comment]
Hi @ageron , I have updated the PR as you suggested (that was right point). If you think it could be described in other way, update the section according to your preferences.
I am sorry for the mess in the commits (extra empty line spoiled the formatting).
Btw - so much thanks for excellent book and your incredible activity here!

**Comment by ageron** [comment]
Merged! Thanks a lot for your contribution and your kind words. :)

**Comment by ChrisQlasty** [comment]
You are welcome!
I see that something else was messed with my PR but you managed to fix it - so again I am sorry for giving you unnecessary jobs. Have to be more focused next time.

**Comment by ageron** [comment]
Oops, I merged a bit too fast, the JSON was actually incorrectly formatted, so Jupyter was unable to load the notebook.  I fixed the problem, everything's okay now.
Jupyter notebooks are great to work with, except that they are a pain to manage as source code. Whenever someone sends me a Pull Request, if they actually run the whole notebook before submitting the PR, then the diff is huge and very hard to read. It's better when you use [nbdime](https://github.com/jupyter/nbdime) to view the notebook diff, but it's still not perfect, in particular it's too slow. I prefer PRs with a small diff that I can easily verify visually, but then if I merge it without actually testing it (like I did above), there's a risk that it will crash the notebook. And since it's Machine Learning, testing the whole notebook can take hours. So I end up only testing the cells that were modified, which isn't great (in this particular case, since it's just comments, I'm confident that the notebook will still have the same output, but in other cases, there might be side-effects that are hard to predict).
That said, thanks again for your contribution, and don't hesitate to send more PRs.

**Comment by ChrisQlasty** [comment]
I agree. Thank you for the valuable comment for the community I believe.

**Pull request merged**
