### PR TITLE
Add link to Deepnote

### PR DESCRIPTION
**Pull request by Jirka-Lhotka**
I like Deepnote more than Jupyter's nbviewer, because it allows you to edit and save the notebooks online as well. I added a link to the instructions list in case anyone else wanted to play around with the code as well.

### CODE REVIEW

**Comment by Jirka-Lhotka** [comment]
Similar service to Mybinder from #190, but more stable and a bit faster from my experience.

**Comment by ageron** [comment]
Hi @Jirka-Lhotka ,
Thanks for your proposal. I did not know about Deepnote. How stable is it? I just tried clicking on the link for chapter 1, and after a few seconds, Deepnote printed an error message "Could not connect to orchestrator, received 502". I had a similar experience with mybinder: I added a link to it almost at the very beginning of this project, and I really thought it was fantastic, but I ended up removing it because of the fact that it would regularly be unavailable or buggy, and people would file issues here.

**Comment by Jirka-Lhotka** [comment]
Hey @ageron, thanks for the prompt response! I switched to Deepnote from mybinder exactly for this reason and haven't really had any problems -- sometimes a library is missing, but generally it has all the main ones. I've experienced the 502 error once, but it fixed itself when I clicked the link again so it wasn't a big issue really.

**Comment by Jirka-Lhotka** [comment]
Hi @ageron, we've done a lot of work on Deepnote to make it more stable. I think it might make more sense for you now. Check it out and let me know!:)

**Comment by ageron** [comment]
Hi @Jirka-Lhotka ,
Cool! I've updated [the README for the 2nd edition](https://github.com/ageron/handson-ml2) to point to Deepnote, as well as a few other options.

**Comment by Jirka-Lhotka** [comment]
Great to hear, thanks for that! And also thanks for pointing out the bug with requirements.txt not being installed automatically; we're working on fixing that!

What are your thoughts on merging this PR? I understand the 2nd version of the book is what you want to push going forward, but I think the readers of the 1st ed could enjoy Deepnote too and I'd love to get some more users on there:)

**Comment by ageron** [comment]
Hi @Jirka-Lhotka ,
Sounds good, thanks for the PR! :)

**Pull request merged**
