### PR TITLE
Visualization of differences between gradient descent methods

### PR DESCRIPTION
**Pull request by daniel-s-ingram**
This is a cool visualization of the three gradient descent methods covered in your book showing all three  converging to the solution on the same plot.

### CODE REVIEW

**Comment by ageron** [comment]
Very nice, @daniel-s-ingram , thanks! Do you think you could put this in a Jupyter notebook instead, using `%matplotlib nbagg` and `import matplotlib.animation as animation` instead, similar to the animations in the notebook for chapter 16?  I had some trouble making your program run on my MacBook because matplotlib does not work properly in a virtualenv, and I'd like to keep the repo as much as possible based on Jupyter notebooks so people can tweak and experiment easily.
Thanks again!

**Comment by daniel-s-ingram** [comment]
No problem, @ageron - will do!

**Comment by daniel-s-ingram** [comment]
Done :)

**Comment by daniel-s-ingram** [comment]
Done :)

**Comment by daniel-s-ingram** [comment]
Hi @ageron, let me know if there is anything else you'd like me to change :smile:

**Comment by ageron** [comment]
Hi @daniel-s-ingram ,
Sorry for the late response, I've been busy this week.  I'll check this by tomorrow.
Thanks so much!  :)
Aurélien

**Comment by ageron** [comment]
Merged! I'll rename the notebook and remove the .py file (I'm trying to keep the project focused on notebooks, with few exceptions).   Thanks again Daniel, I really appreciate it.

**Comment by daniel-s-ingram** [comment]
No problem, @ageron. Thank you for merging my PR!

**Pull request merged**
